use_multiprocessing: true  
n_workers: 32        # Number of parallel workers 
stop_on_multiprocessing_fail: true

# Memory management settings
memory_management:
  monitor_memory: false
  batch_size: 350
  aggressive_gc: true

# Data generation settings  
num_data: 14000       # number of images to generate
setting:  NPE_vary_psf_star_2-100_with_artifact_galaxy_80_irz

seed: 11

# VARIABLE PSF setting
variable_psf: true
variation_factor: 1.0
save_psf_param: true
psf_size: 64

# FIXED PSF setting
psf_type: "moffat"          # "moffat" or "gauss"
morph: 'exp'                

# other setting
n_tiles_per_side: 1         # number of tiles on each side
mag: 17.0                   # 17.0 is default
hlr: 0.5                    # 0.5 is default
pixel_scale: 0.2            # 0.2 is default
layout_name: 'random'       # 'random' or 'grid'
coadd_dim: 2550             # without rotation, image dim is coadd_dim + 1
buff: 0                     # 0 is default
sep: 9.5                    # null is default
bands: ['i', 'r', 'z']                # ['r', 'i', 'z']      # ['i'] is default
noise_factor: 1             # 0.58 is default
dither: false               # False is default
dither_size: 0.5            # 0.5 is default
rotate: false               # False is default
shear_setting: vary         # vary or const
catalog_type: 'wldeblend'   # 'wldeblend' or 'fixed' 

# image artifacts
cosmic_rays: true          
bad_columns: true       

# GALAXY density: per square arcmin, 80 is default  
density: 80                 

# limit the magnitude of a certain band
select_observable: 'i_ab'   # column name in the WeakLensingDeblend catalog
select_lower_limit: null    # minimum magnitude
select_upper_limit: 27      # maximum magnitude


# Star configuration
generate_star: true # set to false to disable star catalog
star_bleeds: true 

# STAR density
star_config:
  max_density: 100 
  # density: 10 

# whether to filter star
star_setting:
  star_filter: false
  star_filter_mag: 18.0
  star_filter_band: 'r'

# whether draw bright star
draw_bright: true

